import re
from groq import Groq
from config import GROQ_API_KEY, LLM_MODEL

_client = Groq(api_key=GROQ_API_KEY)


def llm_score(text: str) -> float:
    """
    Uses Groq to estimate the probability that the given text was AI-generated.
    Returns a float in [0.0, 1.0]. Falls back to 0.5 on any error.
    """
    prompt = (
        "You are an AI-content detection expert. Analyze the following text and respond "
        "with ONLY a single decimal number between 0.0 and 1.0 representing the probability "
        "that this text was generated by an AI language model. "
        "0.0 means certainly human-written; 1.0 means certainly AI-generated. "
        "Do NOT include any explanation, label, or extra characters — output the number only.\n\n"
        f"Text to analyze:\n{text}"
    )
    try:
        response = _client.chat.completions.create(
            model=LLM_MODEL,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.0,
            max_tokens=10,
        )
        raw = response.choices[0].message.content.strip()
        match = re.search(r"\d+(?:\.\d+)?", raw)
        if match:
            return max(0.0, min(1.0, float(match.group())))
        return 0.5
    except Exception:
        return 0.5
